spring:
  spec:
    template:
      spec:
        containers:
          - env:
              - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD



