-- Initial schema creation: Examples table for simple CRUD demonstration
-- This table demonstrates basic Spring Boot JPA operations and validation patterns

CREATE TABLE examples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL,
    
    -- Prevent duplicate names
    CONSTRAINT uk_examples_name UNIQUE (name)
);

-- Create index for efficient name lookups
CREATE INDEX idx_examples_name ON examples (name);

-- Add documentation
COMMENT ON TABLE examples IS 'Demonstration table for basic CRUD operations and Spring Boot patterns';
COMMENT ON COLUMN examples.id IS 'Auto-generated primary key';
COMMENT ON COLUMN examples.name IS 'Unique name identifier for the example';
COMMENT ON COLUMN examples.description IS 'Detailed description of what the example demonstrates';
