-- Migration to create the joined table inheritance structure for Person hierarchy
-- This replaces the simple examples table with a comprehensive user management system

-- Drop the existing examples table as it's no longer needed
DROP TABLE IF EXISTS examples CASCADE;

-- Create the main persons table
CREATE TABLE persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth DATE NOT NULL,
    address VARCHAR(500),
    phone_number VARCHAR(20),
    photo_url VARCHAR(1000),
    
    -- Add constraints (H2-compatible syntax)
    CONSTRAINT chk_date_of_birth_not_future CHECK (date_of_birth <= CURRENT_DATE),
    CONSTRAINT chk_date_of_birth_reasonable CHECK (date_of_birth >= DATEADD('YEAR', -150, CURRENT_DATE)),
    CONSTRAINT chk_phone_number_format CHECK (phone_number IS NULL OR REGEXP_LIKE(phone_number, '^[+]?[0-9\s\-()]{7,20}$'))
);

-- Create the students table (inherits from persons)
CREATE TABLE students (
    person_id BIGINT PRIMARY KEY,
    matriculation_number VARCHAR(20) NOT NULL UNIQUE,
    degree_program VARCHAR(200),
    semester INTEGER,
    study_status VARCHAR(20) NOT NULL,
    cohort VARCHAR(50),
    
    -- Foreign key constraint
    CONSTRAINT fk_students_person_id FOREIGN KEY (person_id) REFERENCES persons (id) ON DELETE CASCADE,
    
    -- Add constraints
    CONSTRAINT chk_semester_positive CHECK (semester IS NULL OR semester > 0),
    CONSTRAINT chk_semester_reasonable CHECK (semester IS NULL OR semester <= 20),
    CONSTRAINT chk_study_status_valid CHECK (study_status IN ('ENROLLED', 'REGISTERED', 'ON_LEAVE', 'EXMATRICULATED', 'GRADUATED'))
);

-- Create the employees table (inherits from persons)
CREATE TABLE employees (
    person_id BIGINT PRIMARY KEY,
    employee_number VARCHAR(20),
    department VARCHAR(200),
    office_number VARCHAR(50),
    working_time_model VARCHAR(20),
    
    -- Foreign key constraint
    CONSTRAINT fk_employees_person_id FOREIGN KEY (person_id) REFERENCES persons (id) ON DELETE CASCADE,
    
    -- Add constraints
    CONSTRAINT chk_working_time_model_valid CHECK (working_time_model IS NULL OR working_time_model IN 
        ('FULL_TIME', 'PART_TIME', 'MINI_JOB', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP')),
    
    -- Unique constraint on employee number if it exists
    CONSTRAINT uk_employees_employee_number UNIQUE (employee_number)
);

-- Create the lecturers table (inherits from employees, which inherits from persons)
CREATE TABLE lecturers (
    person_id BIGINT PRIMARY KEY,
    field_chair VARCHAR(300),
    title VARCHAR(50),
    employment_status VARCHAR(30),
    
    -- Foreign key constraint (references employees, not persons directly)
    CONSTRAINT fk_lecturers_person_id FOREIGN KEY (person_id) REFERENCES employees (person_id) ON DELETE CASCADE,
    
    -- Add constraints
    CONSTRAINT chk_employment_status_valid CHECK (employment_status IS NULL OR employment_status IN 
        ('FULL_TIME_PERMANENT', 'PART_TIME_PERMANENT', 'EXTERNAL', 'VISITING', 'CONTRACT', 'EMERITUS', 'ASSISTANT', 'ASSOCIATE', 'PROFESSOR'))
);

-- Create indexes for performance optimization
CREATE INDEX idx_students_matriculation_number ON students (matriculation_number);
CREATE INDEX idx_students_cohort ON students (cohort);
CREATE INDEX idx_students_study_status ON students (study_status);
CREATE INDEX idx_students_semester ON students (semester);

CREATE INDEX idx_employees_employee_number ON employees (employee_number);
CREATE INDEX idx_employees_department ON employees (department);
CREATE INDEX idx_employees_office_number ON employees (office_number);
CREATE INDEX idx_employees_working_time_model ON employees (working_time_model);

CREATE INDEX idx_lecturers_field_chair ON lecturers (field_chair);
CREATE INDEX idx_lecturers_title ON lecturers (title);
CREATE INDEX idx_lecturers_employment_status ON lecturers (employment_status);

CREATE INDEX idx_persons_date_of_birth ON persons (date_of_birth);
CREATE INDEX idx_persons_phone_number ON persons (phone_number);

-- Add comments for documentation
COMMENT ON TABLE persons IS 'Main table for all person types using joined table inheritance';
COMMENT ON TABLE students IS 'Student-specific data, inherits from persons via person_id';
COMMENT ON TABLE employees IS 'Employee-specific data, inherits from persons via person_id';
COMMENT ON TABLE lecturers IS 'Lecturer-specific data, inherits from employees (and transitively from persons)';

COMMENT ON COLUMN persons.id IS 'Primary key that must match Team 10 database ID for collaboration';
COMMENT ON COLUMN students.matriculation_number IS 'Unique student identification number';
COMMENT ON COLUMN students.study_status IS 'Current enrollment status of the student';
COMMENT ON COLUMN employees.employee_number IS 'Optional employee identification number';
COMMENT ON COLUMN lecturers.employment_status IS 'Type of lecturer employment (permanent, external, etc.)';

-- Insert some example data for testing (optional, can be removed in production)
-- Note: This data is for development/testing purposes only
INSERT INTO persons (date_of_birth, address, phone_number) VALUES
    ('1995-05-15', 'Musterstraße 123, 12345 Berlin', '+49 30 12345678'),
    ('1980-03-22', 'Beispielweg 456, 54321 München', '+49 89 87654321'),
    ('1975-11-08', 'Testplatz 789, 67890 Hamburg', '+49 40 11223344');

-- Insert example student
INSERT INTO students (person_id, matriculation_number, degree_program, semester, study_status, cohort) VALUES
    (1, 'S2023001', 'Computer Science', 3, 'ENROLLED', 'BIN-T-23');

-- Insert example employee
INSERT INTO employees (person_id, employee_number, department, office_number, working_time_model) VALUES
    (2, 'E001', 'IT Support', 'A-101', 'FULL_TIME');

-- Insert example lecturer (must be an employee first)
INSERT INTO employees (person_id, employee_number, department, office_number, working_time_model) VALUES
    (3, 'L001', 'Computer Science Department', 'B-201', 'FULL_TIME');

INSERT INTO lecturers (person_id, field_chair, title, employment_status) VALUES
    (3, 'Software Engineering', 'Prof. Dr.', 'FULL_TIME_PERMANENT');