-- Restore examples table for demonstration purposes
-- This table works alongside the person hierarchy for showing simple CRUD operations

CREATE TABLE examples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL,
    
    -- Add constraint to prevent duplicate names
    CONSTRAINT uk_examples_name UNIQUE (name)
);

-- Add some sample data for demonstration
INSERT INTO examples (name, description) VALUES
    ('Spring Boot Setup', 'Demonstrates basic Spring Boot application setup with JPA, Security, and OpenAPI documentation'),
    ('REST API Design', 'Shows proper REST endpoint design with validation, error handling, and HTTP status codes'),
    ('Database Migration', 'Example of Flyway database migration with constraints and indexes'),
    ('Component Architecture', 'Illustrates the separation of concerns using Controller, Service, Repository, and Component layers'),
    ('Validation Patterns', 'Demonstrates Bean Validation annotations and custom validation logic');

-- Create index for performance
CREATE INDEX idx_examples_name ON examples (name);

-- Add comment for documentation
COMMENT ON TABLE examples IS 'Simple example entities for demonstrating basic CRUD operations and Spring Boot patterns';