name: Code Quality Check (Spotless & Checkstyle)
permissions:
  contents: read

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  code-quality:
    runs-on: ubuntu-latest
    # This condition will skip the workflow when a merge commit is detected
    if: ${{ !startsWith(github.event.head_commit.message, 'Merge') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Check code formatting (Spotless)
        run: ./mvnw spotless:check

      - name: Run logic and complexity checks (Checkstyle)
        run: ./mvnw checkstyle:check
